name: ci-helm-ghcr
permissions:
  packages: write
  contents: read

on:
  push:
    branches:
      - main
  pull_request:

env:
  CHART_NAME: my-chart
  BASE_VERSION: 1.0.0

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Helm
        run: |
          curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Generate Semantic Version
        id: semver
        run: |
          echo "IMAGE_TAG=${{ env.BASE_VERSION }}-${{ github.run_number }}" >> $GITHUB_ENV

      - name: Helm Lint
        run: |
          helm lint .

      - name: Helm Login to GHCR
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Helm Package
        run: |
          helm package . --version $IMAGE_TAG

      - name: Helm Push to GHCR
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: |
          helm push ${{ env.CHART_NAME }}-$IMAGE_TAG.tgz oci://ghcr.io/${{ github.repository_owner }}
